### PR TITLE
More things!

### PR DESCRIPTION
**Pull request by jodyheavener**
Please do not merge yet.

### CODE REVIEW

**Comment by Yeungdb** [comment]
Thanks for putting the config stuff into a helper function! That would definitely clean up a lot of my stuff.

**Comment by jodyheavener** [comment]
@Yeungdb does making the env vars relative to the directory work for you? I did this for the sake of it existing in different locations across different OSes

**Comment by Yeungdb** [comment]
I will need to check with the AWS stuff, if it works on AWS then it would be perfect. The env vars have been most of the trouble with AWS as wsgi doesn't acknowledge them

**Comment by Yeungdb** [comment]
Thanks for adding the SQL Resets!

**Pull request merged**
